services:
  db:
    image: postgres
    container_name: crudapp_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crudapp_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d crudapp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  crudapp:
    build: .
    container_name: crudapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=crudapp_db
    ports:
      - "8080:8080"
